version: "3.9"
networks:
  my_network:
    driver: bridge
services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - my_network
    container_name: database
    environment:
      MYSQL_USER: vinhnc
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs_project
      LANG: C.UTF-8
    ports:
      - 3306:3306
    volumes:
      - C:/Users/htv-Vinhnc/Documents/mysql:/var/lib/mysql/
  # app:
  #   build: 
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - my_network
  #   container_name: app
  #   restart: always
  #   depends_on:
  #     - db
  #   ports: 
  #     - 3000:3000
